[build-system]
requires = ["setuptools>=42", "setuptools-scm", "numpy>=1.7"]
build-backend = "setuptools.build_meta"

[project]
name = "umi_tools"
description = "umi_tools: Tools for UMI analyses"
dynamic = ["version"]
authors = [
    {name = "Ian Sudbery", email = "i.sudbery@sheffield.ac.uk" }
]

keywords = ["computational", "genomics"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Developers",
  "Programming Language :: Python",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
  "Operating System :: POSIX",
  "Operating System :: Unix",
  "Operating System :: MacOS"
]
dependencies = [
    "numpy>=1.7",
    "pandas>=0.12.0",
    "pysam>=0.16.0.1",
    "future",
    "regex",
    "scipy",
    "matplotlib",
    "pybktree",
]

[tool.setuptools]
ext-modules = [
    {name = "umi_tools._dedup_umi", sources = ["umi_tools/_dedup_umi.c"]}
]

[tool.setuptools.packages.find]


[tool.setuptools_scm]

[tool.cibuildwheel]
# This tells cibuildwheel to inject these flags into pip whenever it runs
environment = { PIP_ONLY_BINARY = "numpy", PIP_PREFER_BINARY = "1" }

[tool.ruff]
# Target only the folders you care about
src = ["src", "tests", "umi_tools"]

[tool.ruff.lint]
# Select what rules to check (E and W cover pycodestyle/pep8)
select = ["E", "W"]

ignore = ['E201',  # whitespace after '('
              'E202',  # whitespace before ')'
              'E265',  # block comment should start with '# '
              'E402',  # module level import not at top of file because matplotlib
              'E501',  # line too long (82 > 79 characters)
              'E731',  # do not assign a lambda expression, use a def
              'E722',  # do not use bare except
              'E721',   # Use `is` and `is not` for type comparisons, or `isinstance()` for isinstance checks
              'W191',
              'W391'
]

[project.urls]
Homepage = "https://github.com/CGATOxford/UMI-tools"
Repository = "https://github.com/CGATOxford/UMI-tools"

[project.scripts]
umi_tools = "umi_tools.umi_tools:main"

